[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\temp\vs_cds\slsc_eds_custom_device'

[projects.cd]
path = 'Source\SLSC EDS.lvproj'

[[codegen.steps]]
name = 'Set Conditional Symbol'
type = 'lvSetConditionalSymbol'
project = '{cd}'
symbol = 'CD_Version'
true_value = '2015_2016'
false_value = 'Default'
condition = 'lvVersion < 2017'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\\National Instruments\\NI VeriStand {veristand_version}\\SLSC Plugins\\Modules'
